# Generated by Django 4.2.6 on 2023-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweight',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
