# Generated by Django 4.2.6 on 2023-10-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_emissions', '0002_productweight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceproduct',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_product', to='product_emissions.productgroup'),
        ),
    ]
