# Generated by Django 4.2.6 on 2023-10-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_emissions', '0003_alter_referenceproduct_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='product_emissions.product'),
        ),
    ]
