# Generated by Django 4.2.6 on 2023-10-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_emissions', '0004_alter_productmaterial_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceproduct',
            name='emission_factor_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_product_package', to='product_emissions.emissionfactor'),
        ),
        migrations.AddField(
            model_name='referenceproduct',
            name='emission_factor_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_product_product', to='product_emissions.emissionfactor'),
        ),
        migrations.AddField(
            model_name='referenceproduct',
            name='emission_factor_total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_emissions.emissionfactor'),
        ),
    ]
