# Generated by Django 4.2.6 on 2023-10-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_emissions', '0005_referenceproduct_emission_factor_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceproduct',
            name='emission_factor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_emissions.emissionfactor'),
        ),
    ]
