# Generated by Django 4.2.6 on 2023-10-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agl_base_db', '0001_initial'),
        ('product_emissions', '0008_centerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerproduct',
            name='center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agl_base_db.center'),
            preserve_default=False,
        ),
    ]
